### PR TITLE
replace hardcoded literal with its appropriate symbol

### PR DESCRIPTION
**Pull request by cryptonote-social**
I believe his hardcoded "8" should actually be RegistersCount, just in case anyone tries to create a variant with more/fewer registers.

### CODE REVIEW

**Comment by hyc** [comment]
Your first commit looks correct. The second commit has nothing to do with the topic and should be in a separate PR.

**Comment by cryptonote-social** [comment]
oops, yeah didn't mean to include that one. fixing...

**Comment by cryptonote-social** [comment]
second commit reverted

**Comment by hyc** [comment]
you should have just used git rebase to delete the unintended commit and then force-pushed your branch.

**Comment by cryptonote-social** [comment]
done

**Pull request merged**
