### PR TITLE
Large page support for FreeBSD

### PR DESCRIPTION
**Pull request by tevador**

### CODE REVIEW

**Comment by hyc** [comment]
I thought you decided this wasn't working? https://github.com/tevador/RandomX/issues/71#issuecomment-502865874

**Comment by tevador** [comment]
It's needed because RandomX currently doesn't compile on FreeBSD. This patch has been tested to compile and run in #71.

**Comment by hyc** [comment]
Sure it compiles and runs, but it doesn't seem to do anything useful wrt large pages. Maybe better to just  do
````
#ifdef __FreeBSD__
  return NULL;
#endif

**Comment by tevador** [comment]
I don't see a reason to disable large page allocation on FreeBSD based on one incomplete hashrate report. Do we know for sure it's not working?

BTW xmrig uses a similar way to allocate memory on FreeBSD: https://github.com/xmrig/xmrig/blob/master/src/Mem_unix.cpp#L56 

It uses the `MAP_PREFAULT_READ` flag, but I don't think it's strictly necessary based on [man](https://www.freebsd.org/cgi/man.cgi?mmap):

```
MAP_PREFAULT_READ	Immediately update the calling process's lowest-level
			virtual	address	translation structures,	such as	its
			page table, so that every memory resident page within
			the region is mapped for read access.  Ordinarily
			these structures are updated lazily.  The effect of
			this option is to eliminate any	soft faults that would
			otherwise occur	on the initial read accesses to	the
			region.	 Although this option does not preclude	prot
			from including PROT_WRITE, it does not eliminate soft
			faults on the initial write accesses to	the region.
```
The first access to each large page in RandomX is a write anyways.

**Pull request merged**
